version: "3.9"
services:
  openapi-aggregator-by-tags:
    build: .
    image: romanowalex/openapi-aggregator-by-tags:v1.0
    container_name: openapi-aggregator-by-tags
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8080/manage/health" ]
      interval: 20s
      timeout: 10s
      retries: 10
    ports:
      - "8080:8080"
