spring:
  application.name: openapi-aggregator-by-tags
  main.banner-mode: off

application:
  apis:
    - name: store
      file: openapi/store.yml
      prefix: /store
    - name: order
      file: openapi/order.yml
      prefix: /order
    - name: warehouse
      file: openapi/warehouse.yml
      prefix: /warehouse
    - name: warranty
      file: openapi/warranty.yml
      prefix: /warranty