---
apiVersion: v1
kind: ConfigMap
metadata:
  name: store-openapi-config
  labels:
    app.kubernetes.io/name: store-yml
    app.kubernetes.io/instance: store-yml
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: manual
data:
  store.yml: |-
    openapi: 3.0.1
    info:
      title: Servers application
      contact:
        name: Romanov Alexey
        url: https://romanow.github.io/
        email: romanowalex@mail.ru
      version: 1.0.0
    servers:
      - url: http://localhost:8080
        description: Local server
    paths: { }
